/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.DefaultListModel;
import Modelo.Producto;
import Modelo.Combo;
import Modelo.Pedido; 
import Controlador.servicioCocina;  
import java.util.ArrayList;

/**
 *
 * @author Josué Sánchez
 */
public class pedidoForm extends javax.swing.JFrame {
    
    private Pedido pedidoActual =
        new Pedido(servicioCocina.generarId());

    DefaultListModel<Producto> modeloProductos   = new DefaultListModel<>();
    DefaultListModel<Producto> modeloSeleccionados = new DefaultListModel<>();
    

    /**
     * Creates new form pedidoForm
     */
    public pedidoForm() {
        initComponents();
        
        modeloProductos.addElement(new Producto(1, "Hamburguesa Clásica", 2500, "Individual"));
        modeloProductos.addElement(new Producto(2, "Papas Grandes", 1200, "Individual"));
        modeloProductos.addElement(new Producto(3, "Refresco", 1000, "Bebida"));
        
        
        ArrayList<Producto> productosCombo = new ArrayList<>();
        productosCombo.add(new Producto(1, "Hamburguesa Clásica", 2500, "Individual"));
        productosCombo.add(new Producto(2, "Papas Grandes", 1200, "Individual"));
        productosCombo.add(new Producto(3, "Refresco", 1000, "Bebida"));

        modeloProductos.addElement(new Combo(4, "Combo Clásico", 4200, productosCombo));

        listaProductos.setModel(modeloProductos);
        listaSeleccionados.setModel(modeloSeleccionados);
        
    botonAgregar.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Producto seleccionado = listaProductos.getSelectedValue();
            if (seleccionado != null) {
                modeloSeleccionados.addElement(seleccionado);
                pedidoActual.agregarProducto(seleccionado); 
                actualizarTotal();
            }
        }
    });

    botonEliminar.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            Producto seleccionado = listaSeleccionados.getSelectedValue();
            if (seleccionado != null) {
                modeloSeleccionados.removeElement(seleccionado);
                pedidoActual.eliminarProducto(seleccionado);  
                actualizarTotal();
            }
        }
    });
    
    botonEnviar.addActionListener(evt -> {
    if (pedidoActual.getProductos().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe agregar al menos un producto.");
        return;
    }

    servicioCocina.agregar(pedidoActual);

    javax.swing.JOptionPane.showMessageDialog(this,
            "¡Pedido #" + pedidoActual.getPedidoID()
            + " enviado a cocina!  Total: \u20A1" + pedidoActual.calcularTotal());


    modeloSeleccionados.clear();
    pedidoActual = new Pedido(Controlador.servicioCocina.generarId());
    actualizarTotal();
});
        
    }
    
    private void actualizarTotal() {
        double total = 0;
        for (int i = 0; i < modeloSeleccionados.size(); i++) {
            total += modeloSeleccionados.get(i).getPrecio();
        }
        jlabelTotal.setText("Total: \u20A1" + total);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jlabelTotal = new javax.swing.JLabel();
        botonEnviar = new javax.swing.JButton();
        jlabelDisponibles = new javax.swing.JLabel();
        jlabelSeleccionados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSeleccionados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonAgregar.setText("Agregar");

        botonEliminar.setText("Eliminar");

        jlabelTotal.setText("Total");

        botonEnviar.setText("Enviar a cocina");

        jlabelDisponibles.setText("Disponibles");

        jlabelSeleccionados.setText("Seleccionados");

        jScrollPane1.setViewportView(listaProductos);

        jScrollPane2.setViewportView(listaSeleccionados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonEnviar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabelDisponibles)
                        .addGap(208, 208, 208)
                        .addComponent(jlabelSeleccionados))
                    .addComponent(jlabelTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabelDisponibles)
                    .addComponent(jlabelSeleccionados))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabelTotal)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEnviar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedidoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pedidoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabelDisponibles;
    private javax.swing.JLabel jlabelSeleccionados;
    private javax.swing.JLabel jlabelTotal;
    private javax.swing.JList<Modelo.Producto> listaProductos;
    private javax.swing.JList<Modelo.Producto> listaSeleccionados;
    // End of variables declaration//GEN-END:variables
}
